{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Ônibus Geral - Por Data/Hora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') AS \"Data Hora\",\r\n  qtde_onibus\r\nFROM\r\n  sptrans.total_onibus_geral\r\nWHERE\r\n  to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY\r\n  \"Data Hora\" DESC\r\n\r\n"
    }
   ]
  },
  {
   "title": "Media de Ônibus Geral",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    TO_CHAR(TO_DATE(data_ref, 'YYYYMMDD') + (hora_id_ref::int || ' hours')::interval, 'DD/MM/YYYY HH24:MI') AS \"Data Hora\",\r\n    qtde_onibus AS \"Quantidade de Ônibus\"\r\nFROM sptrans.media_onibus_geral\r\nWHERE\r\n   to_timestamp(data_ref || ' ' || hora_id_ref || ':00', 'YYYYMMDD HH24:MI') BETWEEN $__timeFrom() AND $__timeTo()\r\norder by \"Data Hora\" DESC"
    }
   ]
  },
  {
   "title": "Total Ônibus Geral - Última Carga",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  TO_CHAR(\r\n        TO_TIMESTAMP(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI'), \r\n        'DD/MM/YYYY HH24:MI'\r\n    ) AS \"Data Hora\",\r\n  qtde_onibus AS \"Quantidade\"\r\n  from  sptrans.total_onibus_geral\r\n  ORDER BY \r\n  data_ref desc,\r\n  hora_ref desc\r\n  limit 1"
    }
   ]
  },
  {
   "title": "Média Ônibus  Por Linha - Ultimas 25 linhas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp(data_ref || ' ' || hora_id_ref || ':00', 'YYYYMMDD HH24:MI') AS time,\r\n  let_cod_linha AS linha,\r\n  SUM(qtde_onibus) AS total_onibus\r\nFROM\r\n  sptrans.media_onibus_por_linha\r\nWHERE\r\n  to_timestamp(data_ref || ' ' || hora_id_ref || ':00', 'YYYYMMDD HH24:MI') BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n  time,\r\n  linha\r\nORDER BY\r\n  time ASC\r\nLIMIT 25"
    }
   ]
  },
  {
   "title": "Total Ônibus Por Linha - Últimas 25 linhas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n   to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') AS time,\r\n  let_cod_linha AS linha,\r\n  SUM(qtde_onibus) AS total_onibus\r\nFROM\r\n  sptrans.total_onibus_por_linha\r\nWHERE\r\n to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n  time,\r\n  linha\r\nORDER BY\r\n  time DESC\r\nLIMIT 25\r\n"
    }
   ]
  },
  {
   "title": "Total de todos ônibus por Linha",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp('20240919' || ' ' || '20:04', 'YYYYMMDD HH24:MI') AS data,\r\n  let_cod_linha AS linha,\r\n  let_origem AS origem,\r\n  let_destino  AS destino,\r\n  SUM(qtde_onibus) AS total_onibus\r\nFROM\r\n  sptrans.total_onibus_por_linha\r\nWHERE\r\n to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n  data,\r\n  linha,\r\n  origem,\r\n  destino\r\nORDER BY\r\n  data ASC\r\n"
    }
   ]
  }
 ]
}