{
 "title": "SPTRANS_DASHBOARD_GRAFANA_V0.2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total de linha abaixo da meta (hora anterior)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\nto_timestamp(data_ref || ' ' || hora_id_ref, 'YYYYMMDD HH24:MI') AS \"Data Hora\",\r\nqtde_linhas as Quantidade\r\nfrom sptrans.total_linhas_abaixo_meta\r\n"
    }
   ]
  },
  {
   "title": "Linhas abaixo da meta (hora anterior)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \r\nto_timestamp(data_ref || ' ' || hora_id_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 HOURS' AS \"Data Hora\",\r\nlet_cod_linha as linha,\r\nmeta_qtde_onibus as alvo,\r\navg_qtde_onibus as atingido ,\r\n(meta_qtde_onibus - avg_qtde_onibus) AS diferenca\r\nfrom sptrans.linhas_abaixo_meta\r\n--WHERE\r\n--  to_timestamp(data_ref || ' ' || hora_id_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 HOURS' BETWEEN $__timeFrom() AND $__timeTo()\r\norder by \"Data Hora\" desc, diferenca desc\r\nlimit 20"
    }
   ]
  },
  {
   "title": "Total Ônibus Geral - Última Carga",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  TO_CHAR(\r\n        TO_TIMESTAMP(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI'), \r\n        'DD/MM/YYYY HH24:MI'\r\n    ) AS \"Data Hora\",\r\n  qtde_onibus AS \"Quantidade\"\r\n  from  sptrans.total_onibus_geral\r\n  ORDER BY \r\n  data_ref desc,\r\n  hora_ref desc\r\n  limit 1"
    }
   ]
  },
  {
   "title": "Total de Ônibus Geral - Por Data/Hora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 HOURS' AS \"Data Hora\",\r\n  qtde_onibus\r\nFROM\r\n  sptrans.total_onibus_geral\r\nWHERE\r\n  to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 HOURS' BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY\r\n  \"Data Hora\" DESC"
    }
   ]
  },
  {
   "title": "Total Ônibus Por Linha - Últimas 25 linhas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 HOURS' AS time,\r\n  let_cod_linha AS linha,\r\n  SUM(qtde_onibus) AS total_onibus\r\nFROM\r\n  sptrans.total_onibus_por_linha\r\nWHERE\r\n to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 HOURS' BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n  time,\r\n  linha\r\nORDER BY\r\n  time DESC\r\nLIMIT 25\r\n"
    }
   ]
  },
  {
   "title": "Media de Ônibus Geral",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n      TO_CHAR(  \r\n        to_timestamp(data_ref || ' ' || hora_id_ref, 'YYYYMMDD HH24:MI'), \r\n        'DD/MM/YYYY HH24:MI'\r\n    ) AS \"Data Hora\",   \r\n    qtde_onibus AS \"Quantidade de Ônibus\"\r\nFROM sptrans.media_onibus_geral\r\nWHERE\r\n  to_timestamp(data_ref || ' ' || hora_id_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 HOURS' BETWEEN $__timeFrom() AND $__timeTo()\r\norder by  \"Data Hora\" DESC\r\nlimit 1"
    }
   ]
  },
  {
   "title": "Total de ônibus por Linha",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp('20240919' || ' ' || hora_ref , 'YYYYMMDD HH24:MI') + INTERVAL '3 Hours' AS data,\r\n  let_cod_linha AS linha,\r\n  let_origem AS origem,\r\n  let_destino  AS destino,\r\n  SUM(qtde_onibus) AS total_onibus\r\nFROM\r\n  sptrans.total_onibus_por_linha\r\nWHERE\r\n to_timestamp(data_ref || ' ' || hora_ref, 'YYYYMMDD HH24:MI') + INTERVAL '3 Hours' BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n  data,\r\n  linha,\r\n  origem,\r\n  destino\r\nORDER BY\r\n  data desc \r\n"
    }
   ]
  },
  {
   "title": "Média Ônibus  Por Linha - Ultimas 25 linhas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp(data_ref || ' ' || hora_id_ref || ':00', 'YYYYMMDD HH24:MI') + INTERVAL '3 Hours' AS time,\r\n  let_cod_linha AS linha,\r\n  SUM(qtde_onibus) AS total_onibus\r\nFROM\r\n  sptrans.media_onibus_por_linha\r\nWHERE\r\n  to_timestamp(data_ref || ' ' || hora_id_ref || ':00', 'YYYYMMDD HH24:MI') + INTERVAL '3 Hours' BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n  time,\r\n  linha\r\nORDER BY\r\n  time DESC\r\nLIMIT 25"
    }
   ]
  }
 ]
}